; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude AddNumberFeedback.msg.html

(cl:defclass <AddNumberFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass AddNumberFeedback (<AddNumberFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AddNumberFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AddNumberFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<AddNumberFeedback> is deprecated: use beginner_tutorials-msg:AddNumberFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AddNumberFeedback>) ostream)
  "Serializes a message object of type '<AddNumberFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AddNumberFeedback>) istream)
  "Deserializes a message object of type '<AddNumberFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AddNumberFeedback>)))
  "Returns string type for a message object of type '<AddNumberFeedback>"
  "beginner_tutorials/AddNumberFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AddNumberFeedback)))
  "Returns string type for a message object of type 'AddNumberFeedback"
  "beginner_tutorials/AddNumberFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AddNumberFeedback>)))
  "Returns md5sum for a message object of type '<AddNumberFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AddNumberFeedback)))
  "Returns md5sum for a message object of type 'AddNumberFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AddNumberFeedback>)))
  "Returns full string definition for message of type '<AddNumberFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AddNumberFeedback)))
  "Returns full string definition for message of type 'AddNumberFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AddNumberFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AddNumberFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AddNumberFeedback
))
