; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude AddNumberGoal.msg.html

(cl:defclass <AddNumberGoal> (roslisp-msg-protocol:ros-message)
  ((number_a
    :reader number_a
    :initarg :number_a
    :type cl:integer
    :initform 0)
   (number_b
    :reader number_b
    :initarg :number_b
    :type cl:integer
    :initform 0))
)

(cl:defclass AddNumberGoal (<AddNumberGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AddNumberGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AddNumberGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<AddNumberGoal> is deprecated: use beginner_tutorials-msg:AddNumberGoal instead.")))

(cl:ensure-generic-function 'number_a-val :lambda-list '(m))
(cl:defmethod number_a-val ((m <AddNumberGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:number_a-val is deprecated.  Use beginner_tutorials-msg:number_a instead.")
  (number_a m))

(cl:ensure-generic-function 'number_b-val :lambda-list '(m))
(cl:defmethod number_b-val ((m <AddNumberGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:number_b-val is deprecated.  Use beginner_tutorials-msg:number_b instead.")
  (number_b m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AddNumberGoal>) ostream)
  "Serializes a message object of type '<AddNumberGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'number_a)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'number_a)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'number_a)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'number_a)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'number_b)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'number_b)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'number_b)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'number_b)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AddNumberGoal>) istream)
  "Deserializes a message object of type '<AddNumberGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'number_a)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'number_a)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'number_a)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'number_a)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'number_b)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'number_b)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'number_b)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'number_b)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AddNumberGoal>)))
  "Returns string type for a message object of type '<AddNumberGoal>"
  "beginner_tutorials/AddNumberGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AddNumberGoal)))
  "Returns string type for a message object of type 'AddNumberGoal"
  "beginner_tutorials/AddNumberGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AddNumberGoal>)))
  "Returns md5sum for a message object of type '<AddNumberGoal>"
  "f0d7c56f56ec7ccfaa7a1b1baa325cf2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AddNumberGoal)))
  "Returns md5sum for a message object of type 'AddNumberGoal"
  "f0d7c56f56ec7ccfaa7a1b1baa325cf2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AddNumberGoal>)))
  "Returns full string definition for message of type '<AddNumberGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 number_a~%uint32 number_b~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AddNumberGoal)))
  "Returns full string definition for message of type 'AddNumberGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 number_a~%uint32 number_b~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AddNumberGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AddNumberGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AddNumberGoal
    (cl:cons ':number_a (number_a msg))
    (cl:cons ':number_b (number_b msg))
))
