// Generated by gencpp from file beginner_tutorials/AddNumberGoal.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADDNUMBERGOAL_H
#define BEGINNER_TUTORIALS_MESSAGE_ADDNUMBERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct AddNumberGoal_
{
  typedef AddNumberGoal_<ContainerAllocator> Type;

  AddNumberGoal_()
    : number_a(0)
    , number_b(0)  {
    }
  AddNumberGoal_(const ContainerAllocator& _alloc)
    : number_a(0)
    , number_b(0)  {
  (void)_alloc;
    }



   typedef uint32_t _number_a_type;
  _number_a_type number_a;

   typedef uint32_t _number_b_type;
  _number_b_type number_b;





  typedef boost::shared_ptr< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AddNumberGoal_

typedef ::beginner_tutorials::AddNumberGoal_<std::allocator<void> > AddNumberGoal;

typedef boost::shared_ptr< ::beginner_tutorials::AddNumberGoal > AddNumberGoalPtr;
typedef boost::shared_ptr< ::beginner_tutorials::AddNumberGoal const> AddNumberGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator1> & lhs, const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator2> & rhs)
{
  return lhs.number_a == rhs.number_a &&
    lhs.number_b == rhs.number_b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator1> & lhs, const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0d7c56f56ec7ccfaa7a1b1baa325cf2";
  }

  static const char* value(const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0d7c56f56ec7ccfULL;
  static const uint64_t static_value2 = 0xaa7a1b1baa325cf2ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/AddNumberGoal";
  }

  static const char* value(const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint32 number_a\n"
"uint32 number_b\n"
;
  }

  static const char* value(const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number_a);
      stream.next(m.number_b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddNumberGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::AddNumberGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::AddNumberGoal_<ContainerAllocator>& v)
  {
    s << indent << "number_a: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number_a);
    s << indent << "number_b: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number_b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADDNUMBERGOAL_H
