// Generated by gencpp from file beginner_tutorials/AddNumberResult.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADDNUMBERRESULT_H
#define BEGINNER_TUTORIALS_MESSAGE_ADDNUMBERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct AddNumberResult_
{
  typedef AddNumberResult_<ContainerAllocator> Type;

  AddNumberResult_()
    : number_answer(0)  {
    }
  AddNumberResult_(const ContainerAllocator& _alloc)
    : number_answer(0)  {
  (void)_alloc;
    }



   typedef uint32_t _number_answer_type;
  _number_answer_type number_answer;





  typedef boost::shared_ptr< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> const> ConstPtr;

}; // struct AddNumberResult_

typedef ::beginner_tutorials::AddNumberResult_<std::allocator<void> > AddNumberResult;

typedef boost::shared_ptr< ::beginner_tutorials::AddNumberResult > AddNumberResultPtr;
typedef boost::shared_ptr< ::beginner_tutorials::AddNumberResult const> AddNumberResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::AddNumberResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::AddNumberResult_<ContainerAllocator1> & lhs, const ::beginner_tutorials::AddNumberResult_<ContainerAllocator2> & rhs)
{
  return lhs.number_answer == rhs.number_answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::AddNumberResult_<ContainerAllocator1> & lhs, const ::beginner_tutorials::AddNumberResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed6aad06625459c2f4abdb4611178a77";
  }

  static const char* value(const ::beginner_tutorials::AddNumberResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed6aad06625459c2ULL;
  static const uint64_t static_value2 = 0xf4abdb4611178a77ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/AddNumberResult";
  }

  static const char* value(const ::beginner_tutorials::AddNumberResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint32 number_answer\n"
;
  }

  static const char* value(const ::beginner_tutorials::AddNumberResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number_answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddNumberResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::AddNumberResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::AddNumberResult_<ContainerAllocator>& v)
  {
    s << indent << "number_answer: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number_answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADDNUMBERRESULT_H
