// Auto-generated. Do not edit!

// (in-package beginner_tutorials.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class AddNumberGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.number_a = null;
      this.number_b = null;
    }
    else {
      if (initObj.hasOwnProperty('number_a')) {
        this.number_a = initObj.number_a
      }
      else {
        this.number_a = 0;
      }
      if (initObj.hasOwnProperty('number_b')) {
        this.number_b = initObj.number_b
      }
      else {
        this.number_b = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AddNumberGoal
    // Serialize message field [number_a]
    bufferOffset = _serializer.uint32(obj.number_a, buffer, bufferOffset);
    // Serialize message field [number_b]
    bufferOffset = _serializer.uint32(obj.number_b, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AddNumberGoal
    let len;
    let data = new AddNumberGoal(null);
    // Deserialize message field [number_a]
    data.number_a = _deserializer.uint32(buffer, bufferOffset);
    // Deserialize message field [number_b]
    data.number_b = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'beginner_tutorials/AddNumberGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f0d7c56f56ec7ccfaa7a1b1baa325cf2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint32 number_a
    uint32 number_b
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AddNumberGoal(null);
    if (msg.number_a !== undefined) {
      resolved.number_a = msg.number_a;
    }
    else {
      resolved.number_a = 0
    }

    if (msg.number_b !== undefined) {
      resolved.number_b = msg.number_b;
    }
    else {
      resolved.number_b = 0
    }

    return resolved;
    }
};

module.exports = AddNumberGoal;
